### ISSUE TITLE
Cannot make installation to work

### ISSUE THREAD

**Issue by ssakhavi** [deepmind/torch-hdf5#18]
Hi

I am a Ubuntu 14.04 user.

I am using the same commands that you have given for installing the rock package vut I am constantly getting this error:

Error: Could not find expected file libhdf5.a, or libhdf5.so, or libhdf5.so.\* for hdf5 -- you may have to install hdf5 in your system and/or pass hdf5_DIR or hdf5_LIBDIR to the luarocks command. Example: luarocks install hdf5 hdf5_DIR=/usr/local

But i know that I am giving the library path when I use the 
sudo luarocks install hdf5 LIBHDF5_LIBDIR="/usr/lib/x86_64-linux-gnu/"

What can be the problem?

**Comment by achalddave** [comment]
I was still running into this issue with a local install of HDF5. I tried various ways of setting `HDF5_ROOT`, `HDF5_LIBRARIES`, `HDF5_INCLUDE_DIRS`, but none of these worked. Ultimately, updating my path as suggested [here](http://askubuntu.com/questions/311248/cmake-fails-with-could-not-find-hdf5) did the trick:

````
export PATH="$PATH:/path/to/hdf5-dir/"
````

Just in case this helps someone else who runs into this issue.
