### ISSUE TITLE
Error on write- missing declaration for symbol 'H5P_CLS_DATASET_CREATE_g'

### ISSUE THREAD

**Issue by rudrapoudel** [deepmind/torch-hdf5#22]
Reading is fine but I got following error on writing (myFile:write) on **Mac OS**,

**Example Code:**
require 'hdf5'
local myFile = hdf5.open('write.h5', 'w')
myFile:write("/data/abc", torch.rand(5, 5))
myFile:close()

**Error Message:**
/usr/local/bin/luajit: /usr/local/share/lua/5.1/hdf5/datasetOptions.lua:21: missing declaration for symbol 'H5P_CLS_DATASET_CREATE_g'
stack traceback:
	[C]: in function '__index'
	/usr/local/share/lua/5.1/hdf5/datasetOptions.lua:21: in function '__init'
	/usr/local/share/lua/5.1/torch/init.lua:50: in function </usr/local/share/lua/5.1/torch/init.lua:46>
	[C]: in function 'DataSetOptions'
	/usr/local/share/lua/5.1/hdf5/group.lua:70: in function '_writeData'
	/usr/local/share/lua/5.1/hdf5/group.lua:175: in function 'write'
	/usr/local/share/lua/5.1/hdf5/file.lua:60: in function 'write'
	scripts/working.lua:49: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:129: in main chunk
	[C]: at 0x010b1c5100

**Comment by d11** [comment]
Hmm, which version of libhdf5 are you using?

**Comment by rudrapoudel** [comment]
hdf5-1.8.14, thanks!

**Comment by d11** [comment]
Hi there, thanks for the info! It seems the names of some values changed in 1.8.14, resulting in an incompatibility. I have now pushed a new version which updates torch-hdf5 to work with 1.8.14, so it should now work for you I hope. The change means it will no longer be compatible with previous versions.

**Comment by szagoruyko** [comment]
ubuntu 14.04 is broken because of that

**Comment by d11** [comment]
Hmm, yes. I might have been a bit eager. In general I'd prefer not to complicate the code by supporting multiple versions. But I might make an exception here. (Haven't time to do that immediately, but happy to accept patches if you can't wait for me to get around to it.)

**Comment by soumith** [comment]
should be fixed via https://github.com/deepmind/torch-hdf5/pull/29

**Comment by mememimis** [comment]
Hi guys, i have the same problem on 18.02 with hdf5 1.10. Any ideas how can be fixed?

**Comment by nwpuer-ldy** [comment]
> Hi guys, i have the same problem on 18.02 with hdf5 1.10. Any ideas how can be fixed?
Hi, have you fixed this problem?

**Comment by nilinykh** [comment]
Same problem here, Ubuntu 18.03, hdf5 1.10.

**Comment by achiatti** [comment]
Replacing the values in line 28 of ~/torch/install/share/lua/5.1/hdf5/datasetOptions.lua
with the 3 numbers returned by `print(hdf5.version)` fixed it for me (running on Ubuntu 18.04)

For example, in the case of version 1.10.4:
`if hdf5.version[1] >= 1 and hdf5.version[2] >= 10 and hdf5.version[3] >= 4 then
       self._creationProperties = hdf5.C.H5Pcreate(hdf5.C.H5P_CLS_DATASET_CREATE_ID_g)`
