### ISSUE TITLE
Manual not up to date about reading files

### ISSUE THREAD

**Issue by zygmuntz** [deepmind/torch-hdf5#25]
The instructions don't work for me: the hdf5 object has no open(), only open_file(). Also, what to do after opening the file?

th> h = require "hdf5"
                                                                      [0.0001s]	
th> h.op
opaque     open_file  

th> h.open_file( 'train.hdf5' )
cdata<struct 3519>: 0x412f8808
                                                                      [0.0002s]	
th> f = h.open_file( 'train.hdf5' )
                                                                      [0.0002s]

**Comment by d11** [comment]
Hi, I suspect you've installed this: http://colberg.org/lua-hdf5/reference.html. That is a different package, which has subsequently been added to the central luarocks server under the same name as this project. I may need to rename this one to avoid confusion.

**Comment by zygmuntz** [comment]
Amazing, but true! Thanks. You may want to update install instructions for Ubuntu 14 (and possibly other versions):

git clone https://github.com/deepmind/torch-hdf5
cd torch-hdf5
sudo luarocks install hdf5-0-0.rockspec LIBHDF5_LIBDIR="/usr/lib/x86_64-linux-gnu/"

**Comment by d11** [comment]
Thanks! Sorry for the confusion.
