### ISSUE TITLE
module 'util' not found

### ISSUE THREAD

**Issue by malmaud** [deepmind/torch-hdf5#27]
I tried installing on a fresh Docker image based on Ubuntu 14.04. I followed these instructions, which succeeded without incident: 

> sudo apt-get install libhdf5-serial-dev hdf5-tools
git clone git@github.com:deepmind/torch-hdf5.git
cd torch-hdf5
luarocks make hdf5-0-0.rockspec LIBHDF5_LIBDIR="/usr/lib/x86_64-linux-gnu/"

In a ``th`` session, I then get the following error:

> require 'hdf5'
/usr/local/share/lua/5.1/fn/init.lua:1: module 'util' not found:
	no field package.preload['util']
	no file './util.lua'
	no file '/usr/local/share/luajit-2.0.3/util.lua'
	no file '/usr/local/share/lua/5.1/util.lua'
	no file '/usr/local/share/lua/5.1/util/init.lua'
	no file './util.so'
	no file '/usr/local/lib/lua/5.1/util.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/fn/init.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/logroll/init.lua:6: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/hdf5/init.lua:13: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: at 0x004061d0

**Comment by soumith** [comment]
luarocks install https://raw.githubusercontent.com/torch/rocks/master/util-0-0.rockspec

**Comment by malmaud** [comment]
Thanks, that worked.

**Comment by soumith** [comment]
cc: @d11 you probably want to add this to the rockspec

**Comment by d11** [comment]
Thanks all. I have removed the logroll dependency so that util should no longer be needed.
