### ISSUE TITLE
[CentOS6.5] can't load hdf5

### ISSUE THREAD

**Issue by adamist521** [deepmind/torch-hdf5#32]
`luarocks make` is successful but can't load library.
Any idea?
Using torch-distro btw.

```
th> require 'hdf5'
...himada/torch-distro/install/share/lua/5.1/trepl/init.lua:354: .../shimada/torch-distro/install/share/lua/5.1/hdf5/ffi.lua:29: /usr/local/lib/libhdf5.a: invalid ELF header
stack traceback:
	[C]: in function 'error'
	...himada/torch-distro/install/share/lua/5.1/trepl/init.lua:354: in function 'f'
	[string "local f = function() return require 'hdf5' en..."]:1: in main chunk
	[C]: in function 'xpcall'
	...himada/torch-distro/install/share/lua/5.1/trepl/init.lua:620: in function 'repl'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x004057d0	
```

**Comment by d11** [comment]
I'd guess this is a problem with your hdf5 installation itself rather than torch-hdf5. Do the tools that come with it work (e.g h5dump)?

**Comment by adamist521** [comment]
I was able to see the data with h5dump. 
With python, I was able to create and read data so I think it's problem on Torch7...

**Comment by d11** [comment]
Hmm. It's saying it can't load the hdf5 library from /usr/local/lib/libhdf5.a - perhaps experiment with moving that file out of the way and rebuilding, so that it picks up the .so instead...

**Comment by adamist521** [comment]
You were right! It worked when I tried with `libhdf5.so` file.
Is `hdf5.a` not necessary? 
I didn't have much knowledge on dependencies of library and luarocks so I editted `config.lua` manually to look for the `.so` file... 
Thx for the help.

**Comment by d11** [comment]
OK great, thanks. That should work fine for you - the static (.a) version is not needed for torch-hdf5. It's a little puzzling that it did this though; cmake should be finding the dynamic version by default, I think...
How did you install hdf5, out of interest?

**Comment by adamist521** [comment]
hdf5 was installed through yum.
What I did was I first installed hdf5 and hdf5-devel. Then I found out that `.a` file was missing so I tried to install hdf5-static. Then it said that it is only supported till 1.8.5-patch so I downgraded hdf5 from 1.8.7 to 1.8.5 and installed hdf5-static. But it didn't fix the problem so I tried modifying the `configure.lua` of hdf5 and it solved problem.

**Comment by d11** [comment]
I see, thanks for the info. I guess hdf5-static being present is what confused it, but if it's working now then I'd leave it alone. :)

**Comment by adamist521** [comment]
OK. Thanks for everything.
