### ISSUE TITLE
Segfault when loading HDF5 package from worker thread

### ISSUE THREAD

**Issue by gheinrich** [deepmind/torch-hdf5#42]
The following snippet causes a segfault:

```
-- crashes if following line is commented out
--require('hdf5')
local threads = require 'threads'
threadPool = threads.Threads(1,function(threadid) require('hdf5') end )
threadPool:addjob(function()  -- do work
end )
threadPool:synchronize()
threadPool:terminate()
```

**Comment by moconnor725** [comment]
Success.  Thanks.

**Comment by soumith** [comment]
Greg, it looks like hdf5 crashes when being garbage collected from the thread. Looks like a deep issue in the hdf5 lib possibly. I'm looking into it.

**Comment by soumith** [comment]
Indeed, trying it out with hdf5 version 1.8.15, it no longer segfaults. The issue is present in 1.8.13 (ubuntu 14.04's default hdf5)

**Comment by gheinrich** [comment]
Thanks @soumith. I suppose I will have to live with the workaround (loading hdf5 from the main thread). Upgrading to a newer hdf5 library sounds painful. I am closing this issue as it sounds like there isn't much that can be done to address this problem in https://github.com/deepmind/torch-hdf5.
