### ISSUE TITLE
read/write error on Mac OS X

### ISSUE THREAD

**Issue by spiridonovpolytech** [deepmind/torch-hdf5#50]
Hello,
I'm having some issues writing and reading to hdf5 files.

Installed using instructions. (also tried hdf5-20-0 from luarocks install.) HDF5 is ver. 1.8.16 (also tried with 1.8.14).
Below is the exact input I've used:

----
Aleksandrs-MacBook-Pro:~ aleksandrspiridonov$ luajit
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/

 _____              _     
|_   _|            | |    
  | | ___  _ __ ___| |__  
  | |/ _ \| '__/ __| '_ \ 
  | | (_) | | | (__| | | |
  \_/\___/|_|  \___|_| |_|

JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
th> require 'torch'
th> require 'hdf5'
th> local myFile = hdf5.open('/Users/aleksandrspiridonov/t7test/h5test6.h5','w')
th> myFile:write('dataset1', torch.rand(5, 5))
stdin:1: attempt to index global 'myFile' (a nil value)
stack traceback:
	stdin:1: in main chunk
	[C]: at 0x0109fb1ba0
th> 

----
myFile:close() throws the same error. The files do get created but have a zero size.
Has anyone come across this before or recognize the error?

**Comment by soumith** [comment]
if you are doing things in the interperter, drop the "local" keyword from your code. The local variables only survive the scope, and in this case the scope is a line by line of the interpreter.

myFile = hdf5.open('/Users/aleksandrspiridonov/t7test/h5test6.h5','w')

**Comment by spiridonovpolytech** [comment]
Thanks, that fixed it. Just another Lua newbie here.
