### ISSUE TITLE
Installing on Lua 5.3

### ISSUE THREAD

**Issue by alexbw** [deepmind/torch-hdf5#53]
Currently, there is an incompatible dependency in BitOp for Lua 5.3. Is bitop strictly necessary?

**Comment by d11** [comment]
require 'bit' is used in a few places for checking flags and such. What's the Lua 5.3 alternative?

**Comment by alexbw** [comment]
lua-bitop, the Lua 5.1 and 5.2 library that adds LuaJIT-compatible bit ops,
is not compatible with 5.3, and there seems no plans for support of it. It
has its own native bit operations, but perhaps you're not interested in
having two codepaths.

**Comment by d11** [comment]
Yes, since 5.1 and 5.2 are not going anywhere, I think that if 5.3 support is needed it would be neater to just have a compatibility library - separate from lua-bitop if necessary. Otherwise every project that needs to do bit operations has to handle all the versions, which is not so nice.

**Comment by alexbw** [comment]
Agreed.
