### ISSUE TITLE
module 'bit' not found

### ISSUE THREAD

**Issue by jdriesen0908** [deepmind/torch-hdf5#57]
Hi,

I've been trying to switch my torch install from luaJIT to lua5.2, because of luaJIT's 2GB memory limit. However, upon switching, torch-hdf5 won't load anymore, complaining that the module 'bit' is not present. 

.../torch/install/share/lua/5.2/trepl/init.lua:384: module 'bit' not found:No LuaRocks module found for bit

Is it possible I'm doing something wrong?

Thanks

**Comment by soumith** [comment]
luarocks install luabitop

**Comment by jdriesen0908** [comment]
Wow, that was fast! :)

Thanks a million!

**Comment by rabi1993** [comment]
Yes, I also got problem removed using luarocks install luabitop
