### ISSUE TITLE
Can torch-hdf5 support variable-length types?

### ISSUE THREAD

**Issue by jinghuangzhu** [deepmind/torch-hdf5#66]
h5py support variable-length types, for example, my data contains different length of time series data
of size (6, 40), (10, 40), (15, 40) ..., the first dimension varies.

Can torch-hdf5 read in the data and process them? how? Thanks.

**Comment by d11** [comment]
I don't think I added any support for this, mainly because Torch Tensors have to be of fixed dimensionality. Sorry!

**Comment by tmbdev** [comment]
He is referring to this feature: http://docs.h5py.org/en/latest/special.html#arbitrary-vlen-data

That's pretty common in HDF5 datasets. It works with standard fixed size/fixed dim tensors in Python, Julia, etc.
