### ISSUE TITLE
Unsupported HDF5 version 1.10.0

### ISSUE THREAD

**Issue by GPistre** [deepmind/torch-hdf5#67]
I get an error: Unsupported HDF5 version 1.10.0 when importing hdf5 with torch or luajit. Does the package still only supports 1.8? Will it be updated anytime soon?

**Comment by d11** [comment]
I'm afraid I have not tried it, and I don't currently have plans to update it.
If you wanted, you could try changing https://github.com/deepmind/torch-hdf5/blob/master/luasrc/ffi.lua#L70 to allow use with 1.10.0, but I don't know whether it will work or not.
If you find it works OK, I am happy to accept a pull-request updating it.

**Comment by TimZaman** [comment]
Not to be a necromancer but I've tried it and doesn't work even if i change the version to allow for 1.10.
`hdf5/ffi.lua:63: missing declaration for symbol 'H5open'`

**Comment by odhinnsrunes** [comment]
Ubuntu 17.04 ships with 1.10.xx.  I am now unable to use torch-hdf5 based things like torch-rnn.

Is it possibly time to update to work with the newer version as it is the shipping version?
