### ISSUE TITLE
sudo yum install libhdf5-serial-dev hdf5-tools : libhdf5-serial-dev and hdf5-tools not available

### ISSUE THREAD

**Issue by AdityaChaganti** [deepmind/torch-hdf5#77]
Hey guys,

I try to run sudo yum install on my redhat instance: libhdf5-serial-dev hdf5-tools, but come up with the following error log:

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.solarvps.com
 * epel: mirror.cogentco.com
 * extras: mirror.cs.pitt.edu
 * updates: ftp.osuosl.org
No package libhdf5-serial-dev available.
No package hdf5-tools available.
Error: Nothing to do

Any help?

**Comment by nabeelahmed** [comment]
The package for CentOS is named hdf5-devel:
`sudo yum -y install hdf5-devel`

[Source](http://stackoverflow.com/questions/39927206/yum-install-libhdf5-dev-on-amazon-linux/40603914#40603914)
