### ISSUE TITLE
Issue install torch-hdf5 on Mac os Sierra

### ISSUE THREAD

**Issue by cassiesu** [deepmind/torch-hdf5#83]
I followed all the instructions to install hdf5 on the latest mac os Sierra. However, I cannot require 'hdf5' in torch successfully. 
The error message showed as below. Any help?
/Users/cassiesu/torch/install/share/lua/5.1/trepl/init.lua:384: /Users/cassiesu/torch/install/share/lua/5.1/hdf5/ffi.lua:56: ')' expected near '_close' at line 1436
<img width="568" alt="screen shot 2016-10-04 at 13 37 26" src="https://cloud.githubusercontent.com/assets/11336786/19073045/03245762-8a39-11e6-8fe3-79e4debf48ac.png">

**Comment by tbornt** [comment]
I met the same issue when playing with https://github.com/karpathy/neuraltalk2.
You can find the details https://github.com/neovim/neovim/issues/5455.
I will show you my solution.
Edit `ffi.lua` line 44, 
change 
`local process = io.popen("gcc -E " .. headerPath) -- TODO pass -I`
to
`local process = io.popen("gcc -D '_Nullable=' -E " .. headerPath) -- TODO pass -I`.
Hope it works for you.

**Comment by cassiesu** [comment]
@tbornt Just test it. It works! Thxxxx!

**Comment by nylki** [comment]
Should this change be also the repo? Maybe reopen the issue then? :)

**Comment by ChrisCummins** [comment]
Thanks @tbornt !

**Comment by robertshearing** [comment]
I was having the same problem but none of the fixes worked for me. I'm on MacOS and I managed to fix it by downgrading my Command Line Tools to v7.2.
Refer to this post: [https://github.com/torch/cutorch/issues/522](https://github.com/torch/cutorch/issues/522) for instructions.

**Comment by stanleycyang** [comment]
@tbornt Where is the ffi.lua file located at?

**Comment by Jordan-Campbell** [comment]
I had exactly the same error as the original post, changing line 44 in ffi.lua as per @tbornt worked for me.
